"""Base LLM interface."""

from __future__ import annotations

from abc import ABC, abstractmethod

from app.schemas import RetrievedChunk


class LLMError(RuntimeError):
    """Raised when the LLM backend fails or returns unusable output."""


class BaseLLM(ABC):
    """Interface for answer-generation backends.

    Contract:
    - Output is JSON with keys: answer_text, spoken_citation, limitations,
      next_step. source_ids are NOT generated by the LLM; the caller supplies
      the allowed set and enforces it (see :meth:`enforce_source_ids`).
    - No personal data beyond query text and provided chunks may be sent.
    """

    name: str = "base"

    @abstractmethod
    def generate_answer(
        self,
        query: str,
        chunks: list[RetrievedChunk],
        max_chars: int = 2000,
    ) -> dict:
        """Return a JSON dict with answer fields."""

    def enforce_source_ids(self, parsed: dict, allowed: set[str]) -> dict:
        """Force source_ids from the answer to be a subset of allowed."""
        provided = parsed.get("source_ids") or []
        kept = [sid for sid in provided if sid in allowed]
        if kept != provided:
            parsed["source_ids"] = kept
            parsed["_source_ids_sanitized"] = True
        else:
            parsed["_source_ids_sanitized"] = False
        return parsed
